package com.tbuk.psd2.model.common;

public enum TransactionStatus {
    PROCESSING("PROCESSING"),
    SUCCESS("SUCCESS"),
    FAILURE_INSUFFICIENT_FUNDS("FAILURE_INSUFFICIENT_FUNDS"),
    FAILURE_INVALID_CURRENCY("FAILURE_INVALID_CURRENCY"),
    FAILURE_PERMISSION_DENIED("FAILURE_PERMISSION_DENIED"),
    FAILURE_INVALID_AMOUNT("FAILURE_INVALID_AMOUNT"),
    FAILURE_EXPIRED("FAILURE_EXPIRED"),
    FAILURE_UNSUPPORTED_DESTINATION("FAILURE_UNSUPPORTED_DESTINATION"),
    FAILURE_GENERIC("FAILURE_GENERIC"),
    INITIATED("INITIATED");

    String status;
    TransactionStatus(String st){this.status=st;}
    public String getStatus(){return  this.status;}
}
